# Copyright (c) 2026 Zetta Contributors
"""Lossless mid-episode snapshots for RoboCasa / robosuite environments.

The public ``get_sim_state`` helpers in robosuite only cover a subset of the
state required for an exact continuation.  This module deliberately captures
three separate namespaces:

* every field in MuJoCo's ``mjSTATE_INTEGRATION`` state specification;
* mutable ``MjModel`` arrays that RoboCasa randomization can change; and
* numeric Python-side state held by composite controllers, grippers, recent
  value buffers, observables, and the environment wrappers.

Snapshots are stored as a compressed NPZ plus a JSON manifest.  No pickle
is used, and restoration refuses a model whose dimensions or object names do
not match the snapshot.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from pathlib import Path
from typing import Any

import mujoco
import numpy as np

INTEGRATION_SPEC = mujoco.mjtState.mjSTATE_INTEGRATION
INTEGRATION_FIELD_SPECS = (
    ("time", mujoco.mjtState.mjSTATE_TIME),
    ("qpos", mujoco.mjtState.mjSTATE_QPOS),
    ("qvel", mujoco.mjtState.mjSTATE_QVEL),
    ("act", mujoco.mjtState.mjSTATE_ACT),
    ("qacc_warmstart", mujoco.mjtState.mjSTATE_WARMSTART),
    ("ctrl", mujoco.mjtState.mjSTATE_CTRL),
    ("qfrc_applied", mujoco.mjtState.mjSTATE_QFRC_APPLIED),
    ("xfrc_applied", mujoco.mjtState.mjSTATE_XFRC_APPLIED),
    ("eq_active", mujoco.mjtState.mjSTATE_EQ_ACTIVE),
    ("mocap_pos", mujoco.mjtState.mjSTATE_MOCAP_POS),
    ("mocap_quat", mujoco.mjtState.mjSTATE_MOCAP_QUAT),
    ("userdata", mujoco.mjtState.mjSTATE_USERDATA),
    ("plugin_state", mujoco.mjtState.mjSTATE_PLUGIN),
)

# These are compiled-model values that may be changed by RoboCasa scene,
# fixture, object, lighting, and dynamics randomization.  Derived kinematic
# arrays (xpos/xmat/etc.) intentionally do not appear; mj_forward regenerates
# those from the restored model and integration state.
MODEL_STATE_FIELDS = (
    "body_pos",
    "body_quat",
    "body_mass",
    "body_inertia",
    "body_ipos",
    "body_iquat",
    "body_gravcomp",
    "jnt_pos",
    "jnt_axis",
    "jnt_stiffness",
    "jnt_range",
    "jnt_margin",
    "jnt_solref",
    "jnt_solimp",
    "dof_damping",
    "dof_frictionloss",
    "dof_armature",
    "dof_solref",
    "dof_solimp",
    "geom_pos",
    "geom_quat",
    "geom_size",
    "geom_friction",
    "geom_solref",
    "geom_solimp",
    "geom_margin",
    "geom_gap",
    "geom_rgba",
    "geom_matid",
    "geom_contype",
    "geom_conaffinity",
    "geom_condim",
    "geom_priority",
    "site_pos",
    "site_quat",
    "site_size",
    "site_rgba",
    "cam_pos",
    "cam_quat",
    "cam_fovy",
    "cam_ipd",
    "cam_intrinsic",
    "cam_orthographic",
    "cam_resolution",
    "cam_sensorsize",
    "cam_user",
    "cam_pos0",
    "cam_mat0",
    "cam_poscom0",
    "light_pos",
    "light_dir",
    "light_ambient",
    "light_diffuse",
    "light_specular",
    "light_attenuation",
    "light_cutoff",
    "light_exponent",
    "light_active",
    "light_bulbradius",
    "light_castshadow",
    "light_directional",
    "light_pos0",
    "light_dir0",
    "light_poscom0",
    "mat_emission",
    "mat_metallic",
    "mat_reflectance",
    "mat_rgba",
    "mat_roughness",
    "mat_shininess",
    "mat_specular",
    "mat_texid",
    "mat_texrepeat",
    "mat_texuniform",
    "mesh_pos",
    "mesh_quat",
    "mesh_scale",
    "eq_data",
    "eq_solref",
    "eq_solimp",
    "tendon_lengthspring",
    "tendon_stiffness",
    "tendon_damping",
    "tendon_frictionloss",
    "tendon_range",
    "tendon_margin",
    "tendon_solref_lim",
    "tendon_solimp_lim",
    "tendon_solref_fri",
    "tendon_solimp_fri",
    "actuator_gainprm",
    "actuator_biasprm",
    "actuator_ctrlrange",
    "actuator_forcerange",
    "actuator_actrange",
    "actuator_gear",
)

# Derived MjData caches are normally regenerated by mj_forward.  RoboCasa can
# sample cameras and sensors inside the first control step before every cache
# has converged to the same phase as a normally stepped environment, however.
# Re-pinning the captured values after mj_forward preserves that landing phase
# without changing the canonical mjSTATE_INTEGRATION continuation state.
DATA_CACHE_FIELDS = (
    "xpos",
    "xquat",
    "xmat",
    "xipos",
    "ximat",
    "xanchor",
    "xaxis",
    "geom_xpos",
    "geom_xmat",
    "site_xpos",
    "site_xmat",
    "cam_xpos",
    "cam_xmat",
    "light_xpos",
    "light_xdir",
    "subtree_com",
    "subtree_linvel",
    "subtree_angmom",
    "cinert",
    "cdof",
    "cdof_dot",
    "cvel",
    "cacc",
    "qacc",
    "qfrc_bias",
    "qfrc_passive",
    "qfrc_constraint",
    "qfrc_inverse",
    "qfrc_actuator",
    "actuator_force",
    "cfrc_int",
    "cfrc_ext",
    "sensordata",
)

# These compiled payloads can be hundreds of megabytes in RoboCasa.  They are
# immutable within an episode, so snapshots fingerprint them instead of
# duplicating them.  Restore refuses a fresh environment with different asset
# bytes, while mutable material assignments and colors are saved normally.
STATIC_ASSET_FIELDS = (
    "tex_data",
    "mesh_vert",
    "mesh_normal",
    "mesh_texcoord",
    "mesh_face",
    "mesh_facenormal",
    "mesh_facetexcoord",
    "hfield_data",
)

SCHEMA_VERSION = 2


def unwrap_task_environment(env: Any) -> tuple[Any, Any]:
    """Return ``(gym_wrapper, robosuite_task_env)`` for a Gym RoboCasa env."""

    gym_wrapper = env.unwrapped
    task_env = getattr(gym_wrapper, "env", gym_wrapper)
    if not hasattr(task_env, "sim") or not hasattr(task_env, "robots"):
        raise TypeError(
            "expected a RoboCasa Gym wrapper around a robosuite environment"
        )
    return gym_wrapper, task_env


def raw_model_and_data(env: Any) -> tuple[Any, Any, Any]:
    _, task_env = unwrap_task_environment(env)
    sim = task_env.sim
    return sim, sim.model._model, sim.data._data


def integration_layout(raw_model: Any) -> list[tuple[str, int, int]]:
    layout: list[tuple[str, int, int]] = []
    cursor = 0
    for name, spec in INTEGRATION_FIELD_SPECS:
        size = int(mujoco.mj_stateSize(raw_model, spec))
        layout.append((name, cursor, size))
        cursor += size
    expected = int(mujoco.mj_stateSize(raw_model, INTEGRATION_SPEC))
    if cursor != expected:
        raise RuntimeError(f"integration layout {cursor} != mj_stateSize {expected}")
    return layout


def integration_slice(raw_model: Any, field_name: str) -> slice:
    for name, start, size in integration_layout(raw_model):
        if name == field_name:
            return slice(start, start + size)
    raise KeyError(field_name)


def read_integration_state(env: Any) -> np.ndarray:
    _, raw_model, raw_data = raw_model_and_data(env)
    state = np.empty(
        int(mujoco.mj_stateSize(raw_model, INTEGRATION_SPEC)), dtype=np.float64
    )
    mujoco.mj_getState(raw_model, raw_data, state, INTEGRATION_SPEC)
    return state


def _object_names(raw_model: Any, object_type: Any, count: int) -> list[str | None]:
    return [mujoco.mj_id2name(raw_model, object_type, index) for index in range(count)]


def model_identity(env: Any) -> dict[str, Any]:
    _, raw_model, _ = raw_model_and_data(env)
    dimensions = {
        name: int(getattr(raw_model, name))
        for name in (
            "nq",
            "nv",
            "na",
            "nu",
            "nbody",
            "njnt",
            "ngeom",
            "nsite",
            "ncam",
            "nlight",
            "neq",
            "ntendon",
            "nmat",
            "ntex",
            "nmesh",
            "nmeshvert",
            "nmeshface",
        )
        if hasattr(raw_model, name)
    }
    names = {
        "body": _object_names(raw_model, mujoco.mjtObj.mjOBJ_BODY, raw_model.nbody),
        "joint": _object_names(raw_model, mujoco.mjtObj.mjOBJ_JOINT, raw_model.njnt),
        "geom": _object_names(raw_model, mujoco.mjtObj.mjOBJ_GEOM, raw_model.ngeom),
        "site": _object_names(raw_model, mujoco.mjtObj.mjOBJ_SITE, raw_model.nsite),
        "actuator": _object_names(
            raw_model, mujoco.mjtObj.mjOBJ_ACTUATOR, raw_model.nu
        ),
    }
    asset_digest = hashlib.sha256()
    for field_name in STATIC_ASSET_FIELDS:
        if not hasattr(raw_model, field_name):
            continue
        value = np.ascontiguousarray(getattr(raw_model, field_name))
        asset_digest.update(field_name.encode("utf-8"))
        asset_digest.update(value.dtype.str.encode("ascii"))
        asset_digest.update(np.asarray(value.shape, dtype=np.int64).tobytes())
        asset_digest.update(value.tobytes())
    static_asset_sha256 = asset_digest.hexdigest()
    canonical = json.dumps(
        {
            "dimensions": dimensions,
            "names": names,
            "static_asset_sha256": static_asset_sha256,
        },
        sort_keys=True,
        separators=(",", ":"),
    ).encode("utf-8")
    return {
        "dimensions": dimensions,
        "names": names,
        "static_asset_sha256": static_asset_sha256,
        "sha256": hashlib.sha256(canonical).hexdigest(),
    }


def capture_model_state(env: Any) -> dict[str, np.ndarray]:
    sim, _, _ = raw_model_and_data(env)
    result: dict[str, np.ndarray] = {}
    for field_name in MODEL_STATE_FIELDS:
        if not hasattr(sim.model, field_name):
            continue
        value = np.asarray(getattr(sim.model, field_name))
        if value.dtype.kind not in "biuf":
            continue
        result[field_name] = np.array(value, copy=True)
    return result


def restore_model_state(env: Any, captured: Mapping[str, np.ndarray]) -> None:
    sim, _, _ = raw_model_and_data(env)
    for field_name, snapshot_value in captured.items():
        target = getattr(sim.model, field_name)
        target_array = np.asarray(target)
        if target_array.shape != snapshot_value.shape:
            raise ValueError(
                f"model field {field_name} shape {target_array.shape} != "
                f"snapshot {snapshot_value.shape}"
            )
        target[:] = snapshot_value


def capture_data_cache(env: Any) -> dict[str, np.ndarray]:
    """Capture derived MuJoCo values that can be observed before the next step."""

    _, _, raw_data = raw_model_and_data(env)
    result: dict[str, np.ndarray] = {}
    for field_name in DATA_CACHE_FIELDS:
        if not hasattr(raw_data, field_name):
            continue
        value = np.asarray(getattr(raw_data, field_name))
        if value.dtype.kind not in "biuf":
            continue
        result[field_name] = np.array(value, copy=True)
    return result


def restore_data_cache(env: Any, captured: Mapping[str, np.ndarray]) -> None:
    """Re-pin the capture-time derived cache after ``mj_forward``."""

    _, _, raw_data = raw_model_and_data(env)
    for field_name, snapshot_value in captured.items():
        target = np.asarray(getattr(raw_data, field_name))
        if target.shape != snapshot_value.shape:
            raise ValueError(
                f"data cache {field_name} shape {target.shape} != "
                f"snapshot {snapshot_value.shape}"
            )
        target[:] = snapshot_value


def refresh_render_resources(env: Any) -> bool:
    """Drop cached GPU renderers after mutable visual model data is restored.

    MuJoCo uploads textures when a ``Renderer`` is constructed.  Updating
    ``MjModel.tex_data`` later changes the CPU model but not an already-created
    OpenGL texture.  RoboSuite's patched ``MjSim`` exposes a safe cache closer;
    the next camera observation then constructs a renderer from the restored
    model.  Environments without that cache need no action here.
    """

    sim, raw_model, _ = raw_model_and_data(env)
    refreshed = False
    render_context = getattr(sim, "_render_context_offscreen", None)
    upload_texture = getattr(render_context, "upload_texture", None)
    if callable(upload_texture):
        for texture_id in range(int(raw_model.ntex)):
            upload_texture(texture_id)
        refreshed = True

    # A compatible environment has identical static mesh bytes (enforced by
    # model_identity). Refresh their GPU buffers alongside textures because
    # material or mesh assignments may have changed.
    context = getattr(render_context, "con", None)
    gl_context = getattr(render_context, "gl_ctx", None)
    if context is not None and gl_context is not None:
        gl_context.make_current()
        for mesh_id in range(int(raw_model.nmesh)):
            mujoco.mjr_uploadMesh(raw_model, context, mesh_id)
        for hfield_id in range(int(raw_model.nhfield)):
            mujoco.mjr_uploadHField(raw_model, context, hfield_id)
        refreshed = True

    close_renderers = getattr(sim, "_close_isolated_rgb_renderers", None)
    if callable(close_renderers):
        close_renderers()
        refreshed = True
    # The repository-level stable renderer stores one official Renderer on
    # the MjSim itself. It also owns uploaded GPU model resources and must be
    # rebuilt after mutable material values are restored.
    try:
        from robots.robocasa.stable_renderer import close_persistent_rgb_renderer

        refreshed = close_persistent_rgb_renderer(sim) or refreshed
    except ImportError:
        pass
    return refreshed


def _buffer_owners(robot: Any) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for attribute_name in (
        "recent_actions",
        "recent_qpos",
        "recent_torques",
        "recent_ee_forcetorques",
        "recent_ee_pose",
        "recent_ee_vel",
        "recent_ee_vel_buffer",
        "recent_ee_acc",
    ):
        value = getattr(robot, attribute_name, None)
        if isinstance(value, Mapping):
            for key, item in value.items():
                if hasattr(item, "__dict__"):
                    result[f"buffer.{attribute_name}.{key}"] = item
        elif hasattr(value, "__dict__"):
            result[f"buffer.{attribute_name}"] = value
    return result


def python_state_owners(env: Any) -> dict[str, Any]:
    """Return stable names for Python objects whose values can affect continuation."""

    gym_wrapper, task_env = unwrap_task_environment(env)
    owners: dict[str, Any] = {
        "gym_wrapper": gym_wrapper,
        "task_env": task_env,
    }
    for robot_index, robot in enumerate(task_env.robots):
        prefix = f"robot.{robot_index}"
        owners[prefix] = robot
        composite = getattr(robot, "composite_controller", None)
        if composite is not None:
            owners[f"{prefix}.composite_controller"] = composite
            for name, controller in getattr(composite, "part_controllers", {}).items():
                owners[f"{prefix}.part_controller.{name}"] = controller
        grippers = getattr(robot, "gripper", {})
        if isinstance(grippers, Mapping):
            for name, gripper in grippers.items():
                owners[f"{prefix}.gripper.{name}"] = gripper
        elif hasattr(grippers, "__dict__"):
            owners[f"{prefix}.gripper"] = grippers
        owners.update(
            {f"{prefix}.{name}": item for name, item in _buffer_owners(robot).items()}
        )
    for name, observable in getattr(task_env, "_observables", {}).items():
        owners[f"observable.{name}"] = observable
    return owners


def _numeric_array(value: Any) -> np.ndarray | None:
    if isinstance(value, np.ndarray) and value.dtype.kind in "biuf":
        return np.array(value, copy=True)
    if isinstance(value, (bool, np.bool_)):
        return np.asarray(bool(value), dtype=np.bool_)
    if isinstance(value, (int, np.integer)):
        return np.asarray(int(value), dtype=np.int64)
    if isinstance(value, (float, np.floating)):
        return np.asarray(float(value), dtype=np.float64)
    return None


def _flatten_numeric(
    value: Any,
    *,
    path: tuple[Any, ...] = (),
    depth: int = 0,
) -> list[tuple[tuple[Any, ...], np.ndarray]]:
    direct = _numeric_array(value)
    if direct is not None:
        return [(path, direct)]
    if depth >= 4:
        return []
    result: list[tuple[tuple[Any, ...], np.ndarray]] = []
    if isinstance(value, Mapping):
        for key, item in value.items():
            if isinstance(key, (str, int)):
                result.extend(
                    _flatten_numeric(item, path=(*path, key), depth=depth + 1)
                )
    elif isinstance(value, list):
        for index, item in enumerate(value):
            result.extend(_flatten_numeric(item, path=(*path, index), depth=depth + 1))
    return result


def capture_python_state(
    env: Any,
) -> tuple[dict[str, np.ndarray], list[dict[str, Any]]]:
    arrays: dict[str, np.ndarray] = {}
    manifest: list[dict[str, Any]] = []
    for owner_name, owner in python_state_owners(env).items():
        if not hasattr(owner, "__dict__"):
            continue
        for attribute_name, value in vars(owner).items():
            for subpath, array in _flatten_numeric(value):
                key = f"python_{len(arrays):06d}"
                arrays[key] = array
                manifest.append(
                    {
                        "key": key,
                        "owner": owner_name,
                        "attribute": attribute_name,
                        "subpath": list(subpath),
                        "dtype": str(array.dtype),
                        "shape": list(array.shape),
                    }
                )
    return arrays, manifest


def _restored_value(array: np.ndarray) -> Any:
    if array.shape:
        return np.array(array, copy=True)
    if array.dtype.kind == "b":
        return bool(array)
    if array.dtype.kind in "iu":
        return int(array)
    return float(array)


def _assign_nested(root: Any, path: list[Any], value: Any) -> None:
    if not path:
        raise ValueError("nested assignment requires a non-empty path")
    current = root
    for component in path[:-1]:
        current = current[component]
    current[path[-1]] = value


def restore_python_state(
    env: Any,
    arrays: Mapping[str, np.ndarray],
    manifest: list[dict[str, Any]],
) -> None:
    owners = python_state_owners(env)
    for entry in manifest:
        owner_name = entry["owner"]
        if owner_name not in owners:
            raise KeyError(f"snapshot Python owner is absent: {owner_name}")
        owner = owners[owner_name]
        attribute_name = entry["attribute"]
        value = _restored_value(np.asarray(arrays[entry["key"]]))
        subpath = entry["subpath"]
        if not subpath:
            setattr(owner, attribute_name, value)
        else:
            container = getattr(owner, attribute_name)
            _assign_nested(container, subpath, value)


def capture_snapshot(env: Any) -> tuple[dict[str, np.ndarray], dict[str, Any]]:
    physics = read_integration_state(env)
    model_arrays = capture_model_state(env)
    data_cache_arrays = capture_data_cache(env)
    python_arrays, python_manifest = capture_python_state(env)
    raw_model = raw_model_and_data(env)[1]
    arrays: dict[str, np.ndarray] = {"physics": physics}
    arrays.update({f"model::{name}": value for name, value in model_arrays.items()})
    arrays.update(
        {f"data_cache::{name}": value for name, value in data_cache_arrays.items()}
    )
    arrays.update(python_arrays)
    manifest = {
        "schema_version": SCHEMA_VERSION,
        "model_identity": model_identity(env),
        "integration_layout": integration_layout(raw_model),
        "model_fields": sorted(model_arrays),
        "data_cache_fields": sorted(data_cache_arrays),
        "python": python_manifest,
    }
    return arrays, manifest


def save_snapshot(env: Any, destination: str | Path) -> tuple[Path, Path]:
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    npz_path = destination.with_suffix(".npz")
    manifest_path = destination.with_suffix(".json")
    arrays, manifest = capture_snapshot(env)
    np.savez_compressed(npz_path, **arrays)
    manifest_path.write_text(json.dumps(manifest, indent=2) + "\n", encoding="utf-8")
    with np.load(npz_path, allow_pickle=False) as reloaded:
        for key, original in arrays.items():
            candidate = reloaded[key]
            if (
                original.dtype != candidate.dtype
                or original.shape != candidate.shape
                or original.tobytes() != candidate.tobytes()
            ):
                raise IOError(f"snapshot serialization was not bit-exact for {key}")
    return npz_path, manifest_path


def restore_snapshot(env: Any, source: str | Path) -> dict[str, Any]:
    source = Path(source)
    npz_path = source.with_suffix(".npz")
    manifest_path = source.with_suffix(".json")
    manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    if manifest.get("schema_version") != SCHEMA_VERSION:
        raise ValueError("unsupported RoboCasa snapshot schema")
    live_identity = model_identity(env)
    expected_identity = manifest["model_identity"]
    if live_identity["sha256"] != expected_identity["sha256"]:
        raise ValueError(
            "snapshot model identity mismatch: "
            f"expected {expected_identity['sha256']}, got {live_identity['sha256']}"
        )
    with np.load(npz_path, allow_pickle=False) as stored:
        arrays = {name: np.array(stored[name], copy=True) for name in stored.files}
    model_arrays = {name: arrays[f"model::{name}"] for name in manifest["model_fields"]}
    data_cache_arrays = {
        name: arrays[f"data_cache::{name}"]
        for name in manifest.get("data_cache_fields", ())
    }
    restore_model_state(env, model_arrays)
    _, raw_model, raw_data = raw_model_and_data(env)
    physics = np.ascontiguousarray(arrays["physics"], dtype=np.float64)
    mujoco.mj_setState(raw_model, raw_data, physics, INTEGRATION_SPEC)
    warmstart = np.array(
        physics[integration_slice(raw_model, "qacc_warmstart")], copy=True
    )
    mujoco.mj_forward(raw_model, raw_data)
    if warmstart.size:
        raw_data.qacc_warmstart[:] = warmstart
    restore_data_cache(env, data_cache_arrays)
    restore_python_state(env, arrays, manifest["python"])
    refresh_render_resources(env)
    return manifest


def model_state_difference(env: Any, source: str | Path) -> dict[str, float]:
    source = Path(source)
    manifest = json.loads(source.with_suffix(".json").read_text(encoding="utf-8"))
    current = capture_model_state(env)
    result: dict[str, float] = {}
    with np.load(source.with_suffix(".npz"), allow_pickle=False) as stored:
        for name in manifest["model_fields"]:
            reference = stored[f"model::{name}"]
            candidate = current[name]
            result[name] = (
                float(np.max(np.abs(candidate.astype(float) - reference.astype(float))))
                if reference.size
                else 0.0
            )
    return result
